- hosts: hpclab
  gather_facts: false
  become: true
  pre_tasks:

    - include_role:
        name: dacrystal.lxc
        apply:
          delegate_to: lxdhost
      vars:
        task: instance
        action: launch
        args:
          instance: "{{ inventory_hostname_short }}"
          project: "{{ project }}"
          image: "{{ lxd_image }}"
          description: "Slurm compute image"

  tasks:
    - name: Wait for target connection to become reachable/usable
      wait_for_connection:
      
    - setup:

    - include_role: 
        name: galaxyproject.slurm