- hosts: lxdhost
  collections:
    - ansible.builtin

  gather_facts: false
  become: true
  tasks:
    - name: Destroy cluster containers
      command: lxc delete "{{ item }}" --project {{ project }} --force
      loop: "{{ groups['hpclab'] | map('extract', hostvars, ['inventory_hostname_short']) }}"
    #TODO: Storage/Project...etc 