- hosts: lxdhost
  collections:
    - ansible.builtin

  gather_facts: false
  become: true
  tasks:
    - include_role:
        name: dacrystal.lxc
      vars:
        task: project
        action: delete
        args:
          project: "{{ project }}"
          storage: default